### ISSUE TITLE
Use qemu for arm SVE256

### ISSUE THREAD

**Issue by vineel96** [qemu/qemu-web#5]
Hello,
How can we use qemu to install specifically for arm sve256 instruction set?

**Comment by stsquad** [comment]
The max cpu type gives you all the Arm we can emulate:

```
 -cpu max,sve=on,sve128=on,sve256=on
```

although there are other models that support SVE:

```
  -cpu help
```

See: https://qemu.readthedocs.io/en/v8.1.0/system/arm/cpu-features.html

This is not a support channel, next time see: https://www.qemu.org/support/
